### ISSUE TITLE
After upgrade to @stencil/react-output-target 0.0.7 render fails in react

### ISSUE THREAD

**Issue by kevinng-staizen** [ionic-team/stencil-ds-output-targets#101]
Hello,

After upgrading @stencil/react-output-target from 0.0.6 to 0.0.7 my stencil components are failing silently and failing to render in React.

Inspecting createComponent.tsx it seems this function has changed quite abit. Please help me by providing some guidance on this issue, thanks much for your time.

Expected: After upgrade from 0.0.6 to 0.0.7 stencil components render in React.

Actual: After upgrade to 0.0.7, stencil components fail to render with no error messages.

**Comment by Purii** [comment]
Fixed my build by setting the introduced options:

```js
reactOutputTarget({
      componentCorePackage: "yourcorepackage",
      proxiesFile: "../proxiesFile.ts",
      includeDefineCustomElements: true,
     // includePolyfills: true // Enable if needed
 }),
```

**Comment by jdnichollsc** [comment]
@Purii what polyfills are included here? I can see an issue with the types for React, pointing to stencil package, is this dependency required now?

**Comment by Purii** [comment]
@jdnichollsc I assume these: https://stenciljs.com/docs/browser-support

**Comment by jdnichollsc** [comment]
Ohh perfect, thanks!

**Comment by edolix** [comment]
It would be awesome to have 0.0.8 out soon 🙏

**Comment by sentience** [comment]
0.0.9 is out, but this is still not fixed.

The `includeDefineCustomElements` and `includePolyfills` options are supposed to default to true, and indeed the code looks intended to do that:

https://github.com/ionic-team/stencil-ds-output-targets/blob/b6c0dab984ec1d2933c52a9a844bc7bd81b7586e/packages/react-output-target/src/plugin.ts#L26-L27

Unfortunately, the `normalizeOutputTarget` function containing that code is only called when validating the plugin's configuration:

https://github.com/ionic-team/stencil-ds-output-targets/blob/b6c0dab984ec1d2933c52a9a844bc7bd81b7586e/packages/react-output-target/src/plugin.ts#L10-L12

…not when actually generating the output:

https://github.com/ionic-team/stencil-ds-output-targets/blob/b6c0dab984ec1d2933c52a9a844bc7bd81b7586e/packages/react-output-target/src/plugin.ts#L13-L16

I think the fix would be:

```js
  async generator(config, compilerCtx, buildCtx) { 
    const timespan = buildCtx.createTimeSpan(`generate react started`, true); 

    await reactProxyOutput(config, compilerCtx, normalizeOutputTarget(config, outputTarget), buildCtx.components); 
```

**Comment by ps011** [comment]
Tried to set includeDefineCustomElements to true and built the module. Getting a new error now in the consumer application: 
Can’t import the named export ‘a’ from non EcmaScript module (only default export is available)
Any solutions ? I tried upgrading the version of typescript in the component-library-react package but no luck.

**Comment by sentience** [comment]
@ps011 I'm not seeing the same problem with `includeDefineCustomElements` (and `includePolyfills`) set to `true`.

If you're still stuck, I think you'll need to share a minimal repo demonstrating the issue.

**Comment by aeciolevy** [comment]
I am using version 0.0.9, and it does render unless I do the `defineCustomElements()` in the consumer application.

**Comment by christian-bromann** [comment]
Closing as I believe this should be resolved with the latest version of `@stencil/react-output-target`. If this is still an issue, please let me know and I can re-open this.
