### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by andrewragy** [ionic-team/stencil-ds-output-targets#103]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Add official svelte support!!

**Comment by andrewragy** [comment]
Issue will be put in the main stencil repo

**Comment by adamdbradley** [comment]
The main repo does not deal with output targets such as react, vue and svelte. Issue will be put in this repo.
