### ISSUE TITLE
Angular 10 compatability

### ISSUE THREAD

**Issue by himanshugarg574** [ionic-team/stencil-ds-output-targets#111]
I tried to run this project after upgrading all angular dependencies to v10. It threw an error an relating to [this](https://angular.io/guide/migration-undecorated-classes). This error was due to [this](https://github.com/ionic-team/stencil-ds-output-targets/blob/f515d2c8493d3f0b52c9112d03fe3693960660f1/packages/angular-output-target/resources/control-value-accessors/value-accessor.ts#L4). 

Can be resolved by adding empty Directive decorator.

**Comment by willmartian** [comment]
Resolved in https://github.com/ionic-team/stencil-ds-output-targets/pull/112, closing.
