### ISSUE TITLE
@stencil/vue-output-target broken in 0.1.0 and newer releases

### ISSUE THREAD

**Issue by bjankord** [ionic-team/stencil-ds-output-targets#119]
When using `@stencil/vue-output-target` `0.1.0` or newer, the `vue-component-lib` directory and `utils.ts` file are no longer generated when running `stencil build`.

The generated `component-library-vue/src/proxies.ts` tries to import `defineContainer` from `./vue-component-lib/utils`, but it does exist.

<img width="1231" alt="Screen Shot 2020-09-11 at 4 25 55 PM" src="https://user-images.githubusercontent.com/633148/92974341-99e70480-f44b-11ea-89a0-4cf390f067b9.png">

Repo to reproduce:

1. Clone https://github.com/bjankord/stencil-component-starter-vue-output
2. Install dependencies
3. Run `npm run build` or `yarn build`

This will generate a component-library-vue directory on your machine. Notice that only `component-library-vue/src/proxies.ts` is generated. 

If you bump the version of @stencil/vue-output-target to `0.0.3` in https://github.com/bjankord/stencil-component-starter-vue-output and install that version, then run `npm run build` or `yarn build` you'll see the missing directory/file is generated successfully.

**Comment by christian-bromann** [comment]
This has been fixed and new versions have been released. If this still poses an issue for anyone please let me know and I will re-open the issue.
