### ISSUE TITLE
Fresh Stencil setup with output targets doesn't match working example in this repository

### ISSUE THREAD

**Issue by MrJean** [ionic-team/stencil-ds-output-targets#132]
**Current situation**
Today, I created a fresh Stencil setup and included the output targets for Angular, React and Vue.
After configuring the output targets in `stencil.config.ts` and running `npm run build` (`stencil build --docs`) I don't seem to get the output I was expecting (referencing the output after cloning and running this repository).
The generated Angular folder does only contains `src/directives` and `src/directives/angular-component-lib`, both containing some files.

Config in `stencil.config.ts` regarding `outputTargets`:

```
  outputTargets: [
    angularOutputTarget({
      componentCorePackage: '@some-ds/stencil-component-library',
      directivesProxyFile: '../component-library-angular/src/directives/proxies.ts',
      valueAccessorConfigs: angularValueAccessorBindings,
    }),
    reactOutputTarget({
      componentCorePackage: '@some-ds/stencil-component-library',
      proxiesFile: '../component-library-react/src/components.ts',
    }),
    vueOutputTarget({
      componentCorePackage: '@some-ds/stencil-component-library',
      proxiesFile: '../component-library-vue/src/proxies.ts',
      componentModels: vueComponentModels,
    }),
]
```

Versions in `packages.json`:

```
  "dependencies": {
    "@stencil/angular-output-target": "0.0.5",
    "@stencil/core": "^2.0.1",
    "@stencil/react-output-target": "0.0.9",
    "@stencil/vue-output-target": "^0.1.8"
  },
```

**Question**
Did I configure something wrong?
Are the output targets not supposed to work out of the box?

**Comment by christian-bromann** [comment]
There have been a lot of new releases since this issue has been opened. I can recommend to take a look at https://github.com/stencil-community/designsystem-boilerplate which we build to share some best practice how to setup a design system using Stencil. Let me know if you have further questions.
