### ISSUE TITLE
Question: To use the react-output component do I need to use defineCustomElements(); 

### ISSUE THREAD

**Issue by aeciolevy** [ionic-team/stencil-ds-output-targets#137]
I followed the https://github.com/ionic-team/stencil-ds-output-targets/tree/master/packages/react-output-target/react-component-lib wrapper so I could get react component and use it in a react project.

It does not work if I don't run the `defineCustomElements()` in the react project. 
That is the way it should be? Or using this wrapper I would not need to run the `defineCustomElements()`?

**Comment by zimaah** [comment]
Hey @aeciolevy!

Take a look here: https://stenciljs.com/docs/react#setup-of-react-component-library (pay attention at the `includeDefineCustomElements` property in the `stencil.config.ts`)

**Comment by R-Bower** [comment]
@zimaah I'm wondering if this can be done on a per-component basis.  Currently, it's all or nothing.

**Comment by christian-bromann** [comment]
> I'm wondering if this can be done on a per-component basis. Currently, it's all or nothing.

This could be a great feature , mind raising an issue for this?

I will go ahead and close this issue as there doesn't seem to be anything actionable here. If there are any remaining questions please comment them here and I am happy to answer.
