### ISSUE TITLE
Issue when importing another stencil component and creating binding - Declaration files not generated for dist custom elements bundle

### ISSUE THREAD

**Issue by Arvind6353** [ionic-team/stencil-ds-output-targets#187]
Hi,

I am importing a stencil component library(fw-crayons-core) via global script and trying to generate the react wrapper.

` reactOutputTarget({
      componentCorePackage: 'fw-crayons-extended',
      proxiesFile: '../fw-crayons-react-extended/src/components.ts',
      customElementsDir: 'dist/components',
      includeImportCustomElements: true,
    }),`
    

**the dist-custom-elements target generates 2 folders under dist (after stencil build). 
1) components
2) fw-crayons-core(which is the global stencil component)**

The output react wrapper points to dist/components. Some of the components inside dist/components do not have **.d.ts file** generated for the component
    
 How to deal with this scenario of importing another stencil component ?
  
 Because .d.ts files are not generated for those imported components , the ouput file has issues with import.
 @liamdebeasi 
    
![image](https://user-images.githubusercontent.com/23059431/133934680-80393696-19ec-40c2-b3e8-8260c691e012.png)

**Comment by Arvind6353** [comment]
This issue is similar to #131

**Comment by christian-bromann** [comment]
Closing as we have moved to `@lit/react` which provides a different integration now making this problem disappear. Thanks for raising the issue.
