### ISSUE TITLE
Stale PRs

### ISSUE THREAD

**Issue by klh** [ionic-team/stencil-ds-output-targets#188]
Hi Team,
you're taking so long to review and implement PRs that they turn stale - even the ones that really should get merged in such as:
https://github.com/ionic-team/stencil-ds-output-targets/pull/149
https://github.com/ionic-team/stencil-ds-output-targets/pull/148
https://github.com/ionic-team/stencil-ds-output-targets/pull/129
https://github.com/ionic-team/stencil-ds-output-targets/pull/126

what can we do here....

**Comment by klh** [comment]
@splitinfinities

**Comment by klh** [comment]
bump

**Comment by willmartian** [comment]
Hey @klh, we have had some recent additions to the Stencil and Ionic Framework teams and we will be able to dedicate more resources to this repository going forward, after Ionic v6 is released. Thank you for your patience!
