### ISSUE TITLE
Angular: Incorrect import of interfaces or types in the auto-generated angular directive proxies

### ISSUE THREAD

**Issue by jeannsensei** [ionic-team/stencil-ds-output-targets#197]
Hi. I was using the latest version of @stencil/angular-output-target which is 0.2.0 and the generated proxies produce a wrong  import path. 

For example:

some-component.tsx that has an EventEmitter like this
```
import { SomeInterface } from '../../global/global';

@Event() componentEvent: EventEmitter<SomeInterface>;
```

causes this wrong path in the generated proxies

proxies.ts

```
import { Components } from 'stencil-components';
...
import { SomeInterface as ISomeInterface } from 'stencil-components; <- incorrect
export declare interface SomeComponent extends Components.SomeComponent {}
...

```

the correct path should be 
```
import { Components } from 'stencil-components';
...
import { SomeInterface as ISomeInterface } from 'stencil-components/dist/types/global/global; <- correct
export declare interface SomeComponent extends Components.SomeComponent {}
...

```

To fix this I went back to the 0.1.0 version of @stencil/angular-output-target.
I have to say that for the types, in my package.json I'm pointing to   "types": "dist/types/index.d.ts" since this: https://github.com/ionic-team/stencil-ds-output-targets/issues/139 was happening to me.

Thanks.

**Comment by khronos90** [comment]
I'm having exactly the same issue, also, this latest merge was supposed to fix the `Property 'subscribe' does not exist on type 'EventEmitter<Event>'.ngtsc(2339)`, and it seems to still have it.

Also, to make this work I had to manually change the proxy file generated.

**Comment by splitinfinities** [comment]
Please see https://github.com/ionic-team/stencil-ds-output-targets/issues/139#issuecomment-983016450 for my note about this perferred pattern. It's more maintainable to define your interfaces within one file that you manage and have your package.json's "type" refer to that manually managed file ([sample](https://github.com/ionic-team/stencil-ds-output-targets/blob/v1.0.0/packages/example-project/component-library/package.json#L21)). Just ensure that you `export * from './components'` [like so](https://github.com/ionic-team/stencil-ds-output-targets/blob/v1.0.0/packages/example-project/component-library/src/interfaces.d.ts#L3).
