### ISSUE TITLE
Auto import and define dependencies not working with React wrapper - using dist-custom-elements

### ISSUE THREAD

**Issue by arvindanta** [ionic-team/stencil-ds-output-targets#198]
Hi Team,

I noticed that the below has been fixed in Stencil .
https://github.com/ionic-team/stencil/pull/3039

I see that auto import and defining dependencies is not working with React wrapper.

If a component uses another component, then importing just the parent component doesn't work. I have to import the dependent components as well to make things work. 

Is there a way to solve this issue?

Thanks

**Comment by arvindanta** [comment]
@splitinfinities 
Please find below the sample stencil component library repo. 
https://github.com/arvindanta/stencil-import-error

https://github.com/arvindanta/stencil-import-error/blob/master/src/components/second-component/second-component.tsx#L15


Here second-component internally uses my-component. Am using react output target.

When I import `import { SecondComponent} from import-error/react`

and use `<SecondComponent />`

my-component contents is not getting loaded . my-component is not getting identified as a web component and only the fallback text is getting displayed.


![Screenshot 2021-10-10 at 10 41 57 PM](https://user-images.githubusercontent.com/91056073/136706212-cdb4fa41-4359-4264-98c7-4ad530a4a8ac.png)

**Comment by splitinfinities** [comment]
I'll circle back soon! This Friday at the latest.

**Comment by arvindanta** [comment]
Thank you. With the dist custom elements (though they are tree shakable) , the dependent components are not getting loaded (auto imported and defined as custom elements) by default. We have to manually load the dependent components and define them. I know there is a latest release 2.9.0 that covers this issue. But this might still not work with React wrapper, as the changes are not made here.

**Comment by arvindanta** [comment]
Hi Team, This is one of the key features I was looking for regarding dist-custom-elements target.

The only issue that this is having is now the React wrapper is not tree shakable.

```
**MyComponent = /*@__PURE__*/ proxyCustomElement(MyComponent, [1, "my-component", {
    "first": [1],
    "middle": [1],
    "last": [1]
  }]);**
```

The above function uses re assign MyComponent variable and this gets exported and is breaking the tree shakable ability (which is very imp with React wrapper(custom elements option)).


Instead of reassigning to MyComponent, If I create a new variable and assign it as below
```
let MyComponent1 = /*@__PURE__*/ proxyCustomElement(MyComponent, [1, "my-component", {
    "first": [1],
    "middle": [1],
    "last": [1]
  }]);**
export { **MyComponent1** as M, defineCustomElement as d };
````
Tree shaking is working fine.

Can someone point me to where to handle this change ?

proxyCustomElement is a side effect function and webpack/rollup is tree shaking the modules that uses proxyelement and reassign to the variable.

Please see the attached screenshot. I ran the coverage from chrome dev tools, the statement where **proxyCustomElement** call is getting reassigned to the class component (MyComponent/SecondComponent/ThirdCmp) is getting used while the rest of the code in those modules are unused and this is breaking the tree shaking ability and these modules are bundled together always
 



![Screenshot 2021-10-13 at 9 37 59 AM](https://user-images.githubusercontent.com/91056073/137065631-19cc1db2-6010-4a85-ac34-09a2dc50d899.png)

**Comment by arvindanta** [comment]
@splitinfinities Kindly let me know if you have any update on this . Thanks.

**Comment by christian-bromann** [comment]
Fixed in https://github.com/ionic-team/stencil-ds-output-targets/pull/432
