### ISSUE TITLE
React wrapper treeshaking (dist custom elements) is broken in the Stencil latest release 2.9.0

### ISSUE THREAD

**Issue by arvindanta** [ionic-team/stencil-ds-output-targets#199]
Hi Team,

The React wrapper treeshaking ability is broken in the latest release of Stencil 2.9.0

Have added my observation in the below PR.

https://github.com/ionic-team/stencil/pull/3039

https://github.com/ionic-team/stencil/pull/3039#issuecomment-940223140

https://github.com/ionic-team/stencil-ds-output-targets/issues/198#issuecomment-942251290

Kindly help with it. Thanks

**Comment by liamdebeasi** [comment]
Hi there,

We identified an issue with the wrappers when using autoDefineCustomElements that caused treeshaking to not work properly. This was resolved via https://github.com/ionic-team/stencil-ds-output-targets/pull/208.
