### ISSUE TITLE
Please do NOT fold this into the main repository

### ISSUE THREAD

**Issue by klh** [ionic-team/stencil-ds-output-targets#203]
As you write below, tbh I do not think folding this into the main repo is a good idea, you will potentially make it significantly harder for us to maintain our fixes to this in forks if you do so.

IF you want to do this then make damn sure all pr's are merged and all issues are fixes.

Perhaps the first thing you should concentrate on is creating a proper testsuite for all output targets and all versions possible, and make that pass before you even consider folding this into stencil.

-

Hey folks! Ionic teams are actively working on these bindings, ironing out the details of our repo's and how best to prioritize issues and PR's, as well as updating docs. All of these are big focus areas for us this quarter. Strategically, as the new team has been spinning up, we've been focused on learning about core and the health of the code there. We will be folding this repo into Stencil's process over this quarter once Framework v6 is released. The Angular and React docs are on my plate to have a first draft by the end of this week. 

Can you all do me a huge favor for your next steps? First, detail explicitly what you are bumping into when you open an issue. What PR's are helpful for you? Signal boost the errors that you are bumping into with reactions. We need signal to understand what to prioritize. Please also understand that Framework 6 is releasing soon and that includes all of these updated framework bindings which now use the `dist-custom-elements` output target. So we're all well aware that we need to improve documentation and smooth over the last few rough edges when generated components are used in real environments. 

We're searching for positive signals and GitHub issues like this can be demoralizing to teams of people who are working really hard in iteration each day to improve quite a large ecosystem and community. I want to remind you that there are people on the other end of this code, and I'm super proud of their hard work. 

The way I choose to read this issue is that you're all super engaged community members and - just like myself as a super engaged community member - you want Stencil and its ecosystem to thrive, be successful, and deliver on its promise of being an awesome component compiler. I really appreciate your enthusiasm for Stencil. I'm excited to be able to share more about the hard work happening behind the scenes in order to give the community the confidence in Stencil that we all want. Thank you for the patience and understanding! We'll get there. 

__Originally posted by @splitinfinities in https://github.com/ionic-team/stencil-ds-output-targets/issues/201#issuecomment-963770493__

**Comment by klh** [comment]
Just realized you might have meant "fold this project into the way we work with other stuff" and not "merge this into the main repository" ;) .

I for one will try to dedicate some time this week to go through the pr's, but many of the ones in there and the ones mentioned in my prev issues seem self explanatory.

The problem you have is that these are broken in many different versions so you either have a choice of fixing all latest versions + abandoning support for legacy versions of react, angular etc.

Or 

the long slog of making each major version compatible - which is a daunting task.

But I think a good test harness would really help you get this going.

-k

**Comment by splitinfinities** [comment]
I miscommunicated. We have processes for our repos that we use to pull GitHub issues into Jira. That's what I'm talking about.
