### ISSUE TITLE
Why shall I use the "vue output target" instead of the "vue framework integration"?

### ISSUE THREAD

**Issue by dargmuesli** [ionic-team/stencil-ds-output-targets#204]
Quick question:
This library provides a "vue output target".
The stencil docs however mention the "vue framework integration" without mention of this library's output target (https://stenciljs.com/docs/vue).

**In which case shall I use this library's vue output target** over direct access to the main component library's built `dist`?

---

Note: the documentation's "react framework integration" *does* mention this library's "react output target" (https://stenciljs.com/docs/react).

**Comment by splitinfinities** [comment]
This is a great question! Right now, we're working through how to improve the language for these things. In short, the "vue output target" and the "vue framework integration" are one and the same. We are going to be settling on consistent language for these too, and I'm excited to share more of that soon.
