### ISSUE TITLE
feat: [Angular] Align output with SCAM

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil-ds-output-targets#207]
Produce a single component Angular module file for each component generated from the Angular wrapper function. 

Edit: Capitalization

**Comment by splitinfinities** [comment]
Follow Material Design's lead: https://github.com/angular/components/blob/master/src/material/input/input-module.ts

**Comment by pranav-js** [comment]
much needed. I follow SCAM everywhere, now this is must have in angular project!

**Comment by sean-perkins** [comment]
This feature has shipped and is available with the `includeSingleComponentAngularModules` option: https://stenciljs.com/docs/angular#includesinglecomponentangularmodules
