### ISSUE TITLE
Angular 'generate angular-library finished in 8 ms' is wrong

### ISSUE THREAD

**Issue by khronos90** [ionic-team/stencil-ds-output-targets#210]
The output generated by the Stencil Compiler saying the angular libnrary finished is wrong. Not sure where, but it runs again. 

I'm trying to run a script after that message gets logged by the compiler, the script runs successfully, and the changes get rewritten by the angular output target library. To see an example get any project with the angular output and run this script after
```
export const angularOutputProxyFix = (
  outputTarget: IAngularProxyTarget
): OutputTargetCustom => ({
  type: 'custom',
  name: 'angular-proxy-fix',
  generator: async (
    _config: Config,
    compilerCtx: CompilerCtx
    // buildCtx: BuildCtx
  ) => {
    let runScript = true;
    await new Promise<void>((resolve) => {
      compilerCtx.events.on('buildLog', (log) => {
        if (
          log.messages.findIndex((elm) =>
            elm.includes('generate angular-library finished')
          ) !== -1
        ) {
          resolve();
        }
      });
    });
    // This function changes proxy.ts file
    await runAngularOutputProxyFix(outputTarget);
  }
}
```
No matter what change is done in proxy.ts, it gets re written

**Comment by sean-perkins** [comment]
Hello @khronos90,

Can you explain what change you are needing to make to the generated output? Would it be better to discuss that behavior and get that resolved in the primary package?

Thanks!

**Comment by sean-perkins** [comment]
I am going to close this issue based on the lack of response. If your issue persists, please re-open a new issue. Thanks!
