### ISSUE TITLE
[React] Error: The "path" argument must be of type string (react-output-target)

### ISSUE THREAD

**Issue by jul1ans** [ionic-team/stencil-ds-output-targets#218]
Hi there,

I'm followed the [introduction](https://stenciljs.com/docs/react) and got some error with the react-output-target.
When running `npm run build` in the stencil project, the following error will be thrown:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new
           NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname
           (node:path:654:5) at generateProxies
```

I use the node version 16.13.1 but it also happens with 14.17.3.
Here is my dummy code: https://github.com/jul1ans/stencil-react-issue

Thank you for help :)

**Comment by PatrickKocken** [comment]
I have the exact same issue when following the React Integration. I also tried to downgrade stencil/core and stencil/react-output-target but that didn't work.

Did you managed to find a workaround @jul1ans?

**Comment by jul1ans** [comment]
No I don't. I just wanted to test stencil but I haven't done more research here.

**Comment by sean-perkins** [comment]
Hello @jul1ans and @PatrickKocken thanks for reporting this issue!

After debugging your reproduction app (thank you!), I've been able to diagnose the issue.

In your `stencill/package.json` you are missing a `types` value.

If you add:
```json
"types": "src/components.d.ts",
```

and install the dev dependency that the build will error on:
```
npm install --save-dev workbox-build@4.3.1
```

You will be able to successfully generate the component wrappers. 

Admittedly, we should be definitely warning/erroring a helpful message to the developer about this, as it is likely not mentioned in our documentation. 

Can you let me know if this resolves the issue on your end?
