### ISSUE TITLE
Angular lib doesn't compile when ionicons dependency is added to Stencil lib

### ISSUE THREAD

**Issue by thiagoschmitz** [ionic-team/stencil-ds-output-targets#232]
I've been trying to integrate ionicons to my Stencil project and make it available through my Angular library which is integrated with the Stencil by using angular-output-target.

My ionicons config in the stencil project:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/6010591/154949853-76df5b00-071a-4dff-b81c-c19e50df7484.png">

stencil.config.ts:
`globalScript: 'projects/src/global/global.ts',`

global.ts content:
`import 'ionicons';`

When I try to build my Angular lib I get:
```
✖ Compiling TypeScript sources through NGC
ERROR: projects/spot-angular/src/lib/stencil-generated/components.ts:16:53 - error TS2694: Namespace '"/home/thiago/tooling-spotui-pkg/projects/spot-angular/projects/spot-angular/node_modules/@esw/spot/types/components".Components' has no exported member 'IonIcon'.

16 export declare interface IonIcon extends Components.IonIcon {}
                                                       ~~~~~~~

An unhandled exception occurred: projects/spot-angular/src/lib/stencil-generated/components.ts:16:53 - error TS2694: Namespace '"/home/thiago/tooling-spotui-pkg/projects/spot-angular/projects/spot-angular/node_modules/@esw/spot/types/components".Components' has no exported member 'IonIcon'.

16 export declare interface IonIcon extends Components.IonIcon {}
                                                       ~~~~~~~

See "/tmp/ng-kYzMre/angular-errors.log" for further details.
```

I can see the auto generated components.ts now has:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/6010591/154950356-f66f84df-a3f3-44c2-a7c2-4a591f4604a1.png">

Is it a bug or does anyone know what's going on? Thanks.

**Comment by sean-perkins** [comment]
Hello @thiagoschmitz thanks for reporting this issue!

In Ionic Framework, we have a similar implementation with using `ionicons` and having additional web components that we eventually export through the output targets package. 

Where our implementations differ, is we additionally import and export the namespaced types in our `interface.d.ts`.

```ts
import { Components as IoniconsComponents, JSX as IoniconsJSX } from 'ionicons';

// Existing exports

declare module "./components" {
  export namespace Components {
    export interface IonIcon extends IoniconsComponents.IonIcon{}
  }
}

declare module "./components" {
  export namespace JSX {
    export interface IonIcon extends IoniconsJSX.IonIcon {}
  }
}
```

Your project may not use a file called `interface.d.ts`, but it should coincide with the file that is specified in your `package.json` for the `types` key. 

Can you try adding these changes to your project and let me know if the problem persists? Thanks!

**Comment by thiagoschmitz** [comment]
Thank you very much, @sean-perkins, it solved the build problem!
