### ISSUE TITLE
bug: Vue output modelValue is required

### ISSUE THREAD

**Issue by markbrockhoff** [ionic-team/stencil-ds-output-targets#233]
Hello,

I noticed that the generated types for Vue always require the property v-model to be defined.
This becomes especially noticeable when using tools like vue-tsc or volar for typechecking a vue project.

![image](https://user-images.githubusercontent.com/95471369/156342151-38dbc8d5-7fcb-4117-86cb-9ddf2da33af0.png)

From my understanding, this comes from the interface `InputProps` defined in the generated file vue-component-lib/utils.ts.
Simply making the property `modelValue` optional seemed to fix the problem in my testing.

```ts
export interface InputProps extends Object {
  modelValue?: string | boolean;
}
```

I already created a small PR to implement the suggested fix: #234

**Comment by markbrockhoff** [comment]
Hi @sean-perkins thanks for the quick response. 
Sure, I created a small demo repo containing the stencil-component-starter, the vue-output-target and a simple vue 3 app showing the problem: https://github.com/markbrockhoff/stencil-component-starter
There's a small readme and a demo bash script that sets everything up for you and reproduces the error.

**Comment by sean-perkins** [comment]
Thanks @markbrockhoff! I'll try to clone and validate this weekend, Monday at the latest.

**Comment by markbrockhoff** [comment]
Is there a date when this fix will be released? It'd be great if we could use it as soon as possible
