### ISSUE TITLE
bug: Not recognize global style indicate in stencil.config.ts when import npm in React or Angular project.

### ISSUE THREAD

**Issue by thiagolucio** [ionic-team/stencil-ds-output-targets#269]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

18.2.0

### Current Behavior

When install librarie from npm in React/ Angular (last versions) project and configure the Stencil (even if a very simple project) the `globalStyle: './src/global/app.css',` OR `globalStyle: './src/global/global.scss',` do not recognize from Framework (or React). 

The Stencil.config.ts:

`import { Config } from '@stencil/core';
// import { sass } from '@stencil/sass';

export const config: Config = {
  namespace: 'dsw-minhaconta',
  globalStyle: './src/global/app.css',
  // globalStyle: './src/global/global.scss',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};`

### Expected Behavior

The expected it's recognized global style file. 

### Steps to Reproduce

Step 1:
- create a Stencil (component) project
- go to "stencil.config.ts" file and input  `globalStyle: './src/global/app.css',`  after "namespace" line. 
- create e file inside "src" called "global/app.css"
- inside this file put this code:
`
:root {
  --primary-color: #42a5f5;
  --text-color: #323232;
  --primary-color-base-01: #D60B52;
  --primary-color-base-02: #505050;
}

body {
  background-color: var(--primary-color-base-01)
}

h1 {
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
}
`

- In default created gen component "my-component", change the "return" to :
`<h1 class="titles">Hello, World! I'm {this.getText()}</h1>;` 

- In "my-component.css", include class:
`
.titles {
  font-size: 3.5em;
  font-weight: bold;
  color: var(--primary-color);
}
`
- Save all and run "npm run build" 
- adduser from npm "npm adduser"
- run "npm publish"
- publish project lib in npm...

Step 2 : 
- Create React App "npx create-react-app react-app"
- In index.js from project include (like stencil documentation):
`
import {defineCustomElements} from 'dsw-minhaconta/loader';
defineCustomElements();
`
- In App.js, including:
`
<my-component first="Sem Parar" last="Design System Web"></my-component>
`

- npm install the package (library) from npm:
`
npm i your-npm-package-lib-name
`

- npm start 

### Code Reproduction URL

https://www.npmjs.com/package/design-system-web

### Additional Information

The lib exists in npm and you can import it into your project to see and you don't have to recreate all the steps.

https://www.npmjs.com/package/design-system-web

![Screenshot from 2022-07-02 18-50-32](https://user-images.githubusercontent.com/5756266/177017153-2958968a-bc2e-4798-8408-626b37fec291.png)

**Comment by thiagolucio** [comment]
Any chance? I can help in something?

**Comment by sean-perkins** [comment]
@thiagolucio are you additionally importing the global stylesheet into the DOM (either as part of your app's global stylesheet or from your page/component)? This step is not automatically handled.

The `.titles` styles that are from your component are loading correctly in the DOM.

The styles you have specified in your `globalStyles` exist in the bundle, but are likely not being imported in your project.

**Comment by thiagolucio** [comment]
Yup. I found out a while after picking up a bit.

**Comment by thiagolucio** [comment]
> @thiagolucio are you additionally importing the global stylesheet into the DOM (either as part of your app's global stylesheet or from your page/component)? This step is not automatically handled.
> 
> The `.titles` styles that are from your component are loading correctly in the DOM.
> 
> The styles you have specified in your `globalStyles` exist in the bundle, but are likely not being imported in your project.

Yup. I found out a while after picking up a bit. Thanks anyway!
