### ISSUE TITLE
Adding 'svelte' as a label

### ISSUE THREAD

**Issue by KevsRepos** [ionic-team/stencil-ds-output-targets#272]
The labels for this repository already include labels for the different output targets. There are the 'package: react', 'package: vue' and 'package: angular' labels, but there is no 'package: svelte' label.

I am asking to add a label for the svelte package, so that we can create and filter issues by this label.

**Comment by rwaskiewicz** [comment]
Hey @KevsRepos 👋 

Thanks for the request! 

The Stencil and Ionic Framework teams have collectively decided that we're no longer going to be supporting the Svelte output target. As a result, I'm going to close this issue.

We recently put out a [call to action](https://twitter.com/stenciljs/status/1573025227784740869?cxt=HHwWioCzzYiHwdQrAAAA) to see if anyone would be interested in maintaining it. In the event you're interested, please reach out to Mike (contact details in that tweet). If not, totally understandable!

Thanks again!
