### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by KevsRepos** [ionic-team/stencil-ds-output-targets#273]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

The svelte-output-target is _kind of_ broken. Initially, it doesn't work out of the box. This Issue from 2020 addresses this bug: https://github.com/ionic-team/stencil-ds-output-targets/issues/128

Although since then it wasn't fixed. The solution to manually install the Svelte compiler in the required directory is not acceptable.
I propose to remove the compiler requirement fully out of the svelte-output-target. Why do we need both, the raw Svelte files and the compiled ones?

The raw .svelte files are enough to work with. They would be compiled anyway in a Svelte project.

### Describe the Use Case

First of all, this would be an instant fix to the output target, secondly it makes the whole process less complex.

### Describe Preferred Solution

Remove the compilation of the svelte files from the svele-output-target.

### Describe Alternatives

An alternative would be to at least fix this issue. But I see no point in it.

**Comment by rwaskiewicz** [comment]
Hey @KevsRepos 👋 

Thanks for the request! 

The Stencil and Ionic Framework teams have collectively decided that we're no longer going to be supporting the Svelte output target. As a result, I'm going to close this issue.

We recently put out a [call to action](https://twitter.com/stenciljs/status/1573025227784740869?cxt=HHwWioCzzYiHwdQrAAAA) to see if anyone would be interested in maintaining it. In the event you're interested, please reach out to Mike (contact details in that tweet). If not, totally understandable!

Thanks again!
