### ISSUE TITLE
React Target doesn't pass window `defineCustomElement`

### ISSUE THREAD

**Issue by ncphillips** [ionic-team/stencil-ds-output-targets#29]
This is the output TS
```
/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import { JSX } from 'tinacms-ui';

import { defineCustomElements, applyPolyfills } from 'tinacms-ui/loader';

applyPolyfills().then(() => defineCustomElements());
export const MyComponent = /*@__PURE__*/createReactComponent<JSX.MyComponent, HTMLMyComponentElement>('my-component');

```

This code **will not compile**

It must be passed `defineCustomElement(window)`

**Comment by edolix** [comment]
I'm having the same issue 👍

**Comment by edolix** [comment]
Related to https://github.com/ionic-team/stencil-ds-plugins/commit/8f2dd8019592025c0d1fd20c454d9489ee539ca1#diff-d73f4344de9155f332b25de19546c326R52

**Comment by christian-bromann** [comment]
This issue should be not relevant anymore using the latest `@stencil/react-output-target`. Let me know if this still poses an issue for anyone and I am happy to re-open.
