### ISSUE TITLE
bug: When adding a type or interface to the EventEmitter, the components.ts file won't compile.

### ISSUE THREAD

**Issue by spoodyman** [ionic-team/stencil-ds-output-targets#299]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.15.2

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.4.0

### Current Behavior

When adding a type or interface to the EventEmitter, the components.ts file won't compile.

So for example:

```
import { Event, EventEmitter } from '@stencil/core'

export type TButtonType = 'primary' | 'secondary';
....
export class CustomButton {
....
@Event() buttonType: EventEmitter<TButtonType>;

....
}
```
Will result into a compilation error:

```
Error: .../angular/components.ts:...:... - error TS2305: Module '"...../dist/components"' has no exported member 'TButtonType'.

import type { IButtonType as CustomButtonIButtonType } from '..../dist/components';

Error: ...../angular/components.ts:581:43 - error TS2304: Cannot find name 'TButtonType'.
```

### Expected Behavior

The correct type or interface should be imported

### Steps to Reproduce

1. Create a type / interface
2. Use the type with EventEmitter
3. Build using angular-output-target
4. Try to use in your Angular application
5. You will get a compilation error

### Code Reproduction URL

https://github.com/spoodyman/stencil-angular-output-target-compliation-bug

**Comment by sean-perkins** [comment]
@spoodyman can you confirm that your custom type `TTestType` is being exported from the main entry point of your Stencil library? 

When using types other than inline types, currently the architecture requires that the type be exported from your library directly. 

This is because when the output targets run it will construct an import statement:
```ts
import type { TTestType } from 'your-library-name';
```

instead of trying to resolve the exact location within the bundle that the type is defined.

**Comment by spoodyman** [comment]
Hi,

Sorry for the late reply.
Yes, the fun part is, if you use this typing for a Prop for example, you will get no error at all.

**Comment by spoodyman** [comment]
Okay I get it, I got it to work thank you very much! I updated my repo to a version that works.
