### ISSUE TITLE
Add Github Actions workflow to make sure the autogenerated code can compile

### ISSUE THREAD

**Issue by ncphillips** [ionic-team/stencil-ds-output-targets#30]
## Problem

I very easily found out that this project does not produce usable code with #29 

## Potential Solution

This could be prevented by having a simple CI script that builds a stencil project and then tries to build the autogenerated React code.

**Comment by ncphillips** [comment]
If you make me a collaborator on the repo I will write this workflow

**Comment by jthoms1** [comment]
Added a workflow to test autogenerated code in PR. https://github.com/ionic-team/stencil-ds-output-targets/pull/46
