### ISSUE TITLE
feat(react): Ability to make bindings for transformed tag names at runtime

### ISSUE THREAD

**Issue by raycohen** [ionic-team/stencil-ds-output-targets#311]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

It is possible to create custom tag names to help avoid namespace conflicts, as web components exist in a global namespace. The setup is something like:

```
import { defineCustomElements } from '@stencil/core';

defineCustomElements(window, {
  transformTagName: (tagName) => `custom-${tagName}`,
});
```

From what I can tell, the bindings created by `@stencil/react-output-target` will only use the original tag names, as `createComponentDefinition` receives the original tagName (at build time) and the custom naming occurs at runtime in the browser.

In order to use React component bindings for custom tagNames, we would need to allow calling `createReactComponent` by the application code that uses the built stencil output. To make this possible, we could export `createReactComponent` and the JSX types. 

The resulting usage would look something like this:
```
import { createReactComponent } from "@my-stencil-lib/react-bindings";
import type { JSX } from "@my-stencil-lib/react-bindings";

export const MarketHeader = createReactComponent<JSX.MyHeader, HTMLMyHeaderElement>('custom-my-header');
// ... another call to createReactComponent for each web component from @my-stencil-lib we use
```

### Describe the Use Case

My use case is micro-frontends that are composed at runtime but would like to be able to control their version of a stencil-generated web components package. This would also assist in any situation where web component naming conflicts occur.

### Describe Preferred Solution

I was able to get what I wanted locally by simply adding a couple exports to the generated components.ts. I could see adding this to `generateProxies`, possibly gated by a new key in the `outputTarget` object it receives, if this would need to be done as an opt-in behavior.

If this approach is acceptable, I can attempt a PR for it.

**Comment by sean-perkins** [comment]
Hello and thanks for this feature request!

Transforming the tag name of the web component and/or the react component proxy will unfortunately not satisfy all development constraints of versioning components and I do not believe to be a viable solution for component libraries. 

While being able to transform the selector will allow you to define the web component to different tag names, it does not account for implementation details such as querying an element by a specific selector (`my-component`) or styling attached to a tag name. In these scenarios the web component will not function or display as expected. 

What developers need is [scoped custom element registries](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md). 

I am going to close this request, but I am open to other ideas or approaches for this problem.

Thanks!

**Comment by raycohen** [comment]
> While being able to transform the selector will allow you to define the web component to different tag names, it does not account for implementation details such as querying an element by a specific selector (my-component) or styling attached to a tag name. In these scenarios the web component will not function or display as expected.

I'm not sure I follow what you're saying here. In my use case, those things are manually being accounted for. It works. We added a build step to alter the output from stencil to make it possible. It's just these two lines, but it would be nice if we didn't have to do this, and others might benefit from it as well

```
export { createReactComponent, createOverlayComponent } from './react-component-lib';",
export type { JSX } from '@my-scope/web-components';\n",
```
