### ISSUE TITLE
Angular Ivy Break

### ISSUE THREAD

**Issue by Jefftopia** [ionic-team/stencil-ds-output-targets#32]
Install Angular ^9 and import Angular-wrapped web-components created via the stencil.config.ts output target.

You'll see this error when importing the angular-wrapped component library. 

**Update 2**
It appears that the problem is related to the Ivy compiler and symlinks. Using `preserveSymlink: true` in the angular.json and angularCompiler options did nothing to help. Only creating a release to npm and installing from remote resolved the Ivy build issues for me.

I'd love if someone could shed some light on this.

**Update**
I did some more work following the ionic/ionic repo as an example, this is what I'm now stuck on:

>ERROR Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:899)
    at ɵɵinject (core.js:915)
    at Module.ɵɵdirectiveInject (core.js:20756)
    at NodeInjectorFactory.XdsButton_Factory [as factory] (system-angular.js:97)
    at getNodeInjectable (core.js:5598)
    at instantiateAllDirectives (core.js:12645)
    at createDirectivesInstances (core.js:11881)
    at Module.ɵɵelementStart (core.js:20943)
    at AppComponent_Template (app.component.html:6)
    at executeTemplate (core.js:11841) 

I'm using ng-packager 9, Angular 9, and I'm no longer using the ds-plugins - I'm just using the angular compiler option shipped in stencil 1.8.7. My tsconfig for angular is below.

```json
{
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "flatModuleOutFile": "core.js",
    "flatModuleId": "@system/angular",
    "skipTemplateCodegen": true,
    "fullTemplateTypeCheck": false,
    "enableResourceInlining": true,
    "enableIvy": false
  },
  "compilerOptions": {
    "alwaysStrict": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": true,
    "declarationDir": "dist",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["dom", "es2017"],
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "build/es2015",
    "pretty": true,
    "removeComments": false,
    "importHelpers": true,
    "rootDir": "src",
    "strictPropertyInitialization": false,
    "target": "es2015",
    "baseUrl": ".",
    "paths": {
      "@system/core": ["../core"]
    }
  },
  "exclude": ["node_modules", "src/schematics"],
  "files": ["src/index.ts"]
}
```

>ERROR in getInternalNameOfClass() called on a non-ES5 class: expected XdsBadge to have an inner class declaration

With aot disabled, this warning is thrown in the terminal:

>WARNING in Invalid constructor parameter decorator in /Users/jsmith582/dev/components/packages/angular/dist/fesm2015.js:
 () => [
    { type: ChangeDetectorRef },
    { type: ElementRef },
    { type: NgZone }
]

**Comment by WickyNilliams** [comment]
@Jefftopia hey, did you ever get to the bottom of this? Or manage to use with Angular 9 at all?

**Comment by Jefftopia** [comment]
@WickyNilliams Long story short is yes, I did. I followed the patterns in the ionic project, which is to  say, I'm using NGPackagr and I'm not using the DS plugin. Instead, I'm using the Angular output that's packaged directly into stencil itself. I hope that helps.

**Comment by WickyNilliams** [comment]
Interesting! Can you point me in the direction of what i can look at to get started? Does the built in angular output completely replace the ds-plugin? Does it offer bindings/accessors for forms in angular? I can't find anything on the stencil docs relating to this

**Comment by Jefftopia** [comment]
@WickyNilliams Apologies in advance since I only have rough snippets to share...just don't have the capacity to put together a thorough demo.

core/stencil.config.ts snippet:

```
const angularValueAccessorBindings = [
  {
    elementSelectors: ['my-input'],
    event: 'dsChange',
    targetAttr: 'value',
    type: 'text' as ValueAccessorTypes
  }
];

export const config: Config = {
  namespace: 'my',
  globalStyle: 'src/styles/core.css',
  globalScript: 'src/scripts/index.ts',
  plugins: [
    postcss({
      plugins: [
        postcssImport(),
        postcssNormalize(),
        autoprefixer(),
        tailwindcss('./tailwind.config.js'),
      ]
    })
  ],
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
    angularOutputTarget({
      componentCorePackage: '@my-design/core',
      directivesProxyFile: '../angular/src/directives/proxies.ts',
      directivesUtilsFile: '../angular/src/directives/proxies-utils.ts',
      directivesArrayFile: '../angular/src/directives/proxies-list.txt',
      valueAccessorConfigs: angularValueAccessorBindings
    }),
    reactOutputTarget({
      componentCorePackage: '@my-design/core',
      proxiesFile: '../react/src/components.ts'
    }),
```

In your Angular directory:

angular/src/module.ts:

```
import { NgModule, NgZone, APP_INITIALIZER, ModuleWithProviders, InjectionToken } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { defineCustomElements } from '@my-design/core/loader';
import {
  MyInput,
} from './directives/proxies';

defineCustomElements(window);

const DECLARATIONS = [
  // proxies
  MyInput
];

export function appInit(document: InjectionToken<Document>, ngZone: NgZone) {
}

@NgModule({
  declarations: DECLARATIONS,
  exports: DECLARATIONS,
})
export class myLibraryModule {

  static forRoot(): ModuleWithProviders<MyLibraryModule> {
    return {
      ngModule: MyLibraryModule,
      providers: [
        {
          provide: APP_INITIALIZER,
          useFactory: appInit,
          multi: true,
          deps: [
            DOCUMENT,
            NgZone
          ]
        }
      ]
    }
  }
}
```

angular/tsconfig.json:

```
{
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "flatModuleOutFile": "core.js",
    "flatModuleId": "@my-design/angular",
    "skipTemplateCodegen": true,
    "fullTemplateTypeCheck": false,
    "enableResourceInlining": true,
    "enableIvy": false
  },
  "compilerOptions": {
    "alwaysStrict": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": true,
    "declarationDir": "dist",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["dom", "es2017"],
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "build/es2015",
    "pretty": true,
    "removeComments": false,
    "importHelpers": true,
    "rootDir": "src",
    "strictPropertyInitialization": false,
    "target": "es2015",
    "baseUrl": "."
  },
  "exclude": ["node_modules"],
  "files": ["src/index.ts"]
}
```

angular/package.json
```
{
  "name": "@my-design/angular",
  "version": "0.7.0",
  "description": "angular @my-design",
  "license": "MIT",
  "private": false,
  "repository": {
    "type": "git",
    "url": "my-system.git"
  },
  "scripts": {
    "build": "npm run build.ng",
    "build.ng": "ng-packagr -p package.json",
    "tsc": "tsc -p ."
  },
  "dependencies": {
    "@my-design/core": "^1.0.0",
    "tslib": "^1.11.0"
  },
  "peerDependencies": {
    "@angular-devkit/core": "^9.0.0",
    "@angular-devkit/schematics": "^9.0.0",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/compiler-cli": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/forms": "^9.0.0",
    "@angular/platform-browser": "^9.0.0",
    "@angular/router": "^9.0.0",
    "rxjs": "^6.4.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/core": "^9.0.3",
    "@angular-devkit/schematics": "^9.0.3",
    "@angular/common": "^9.0.2",
    "@angular/compiler": "^9.0.2",
    "@angular/compiler-cli": "^9.0.2",
    "@angular/core": "^9.0.2",
    "@angular/forms": "^9.0.2",
    "@angular/platform-browser": "^9.0.2",
    "@angular/platform-browser-dynamic": "^9.0.2",
    "@angular/router": "^9.0.2",
    "@types/node": "^13.7.4",
    "fs-extra": "^8.1.0",
    "glob": "^7.1.4",
    "ng-packagr": "^9.0.1",
    "rxjs": "^6.5.2",
    "tsickle": "^0.38.0",
    "tslint": "^6.0.0",
    "tslint-ionic-rules": "0.0.21",
    "typescript": "3.6.5",
    "zone.js": "^0.10.2"
  },
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "ngPackage": {
    "lib": {
      "entryFile": "src/index.ts"
    },
    "whitelistedNonPeerDependencies": [
      "@my-design/core"
    ]
  },
  "publishConfig": {
    "access": "public",
    "registry": "your-registry"
  },
  "main": "dist/bundles/dse-design-angular.umd.js",
  "module": "dist/fesm5/dse-design-angular.js",
  "es2015": "dist/fesm2015/dse-design-angular.js",
  "esm5": "dist/esm5/dse-design-angular.js",
  "esm2015": "dist/esm2015/dse-design-angular.js",
  "fesm5": "dist/fesm5/dse-design-angular.js",
  "fesm2015": "dist/fesm2015/dse-design-angular.js",
  "typings": "dist/dse-design-angular.d.ts",
  "metadata": "dist/dse-design-angular.metadata.json",
  "sideEffects": false
}
```

Again, this is all taken from https://github.com/ionic-team/ionic/tree/master/angular, except I have no custom schematics which simplifies my build relative to theirs. I hope these snippets help. Happy to answer clarifying questions.

**Comment by viljamis** [comment]
@Jefftopia Thanks, this is really useful!

**Comment by Jefftopia** [comment]
@viljamis Let me know how it goes!

**Comment by WickyNilliams** [comment]
Hey, just to follow up on this... 

I tested again today with angular 9 and 10, and everything is working this time. I'm not sure what's changed, but i've upgraded stencil and the output targets multiple times since I last tried. Perhaps there was a fix in there somewhere.

**Comment by lodybo** [comment]
I dove into this issue today and I managed to get things working using the directions described [here](https://github.com/angular/angular/issues/25813#issuecomment-584866010).

Basically, I had to adjust the `tsconfig.json` file in my Angular app directory (the app that consumes the Stencil Angular library) and add the sources for Angular to the `paths` property (I didn't need to add the paths to my Stencil project):

```javascript
{
  // ...,
  "compilerOptions": {
    // ...,
    "paths": {
      "@angular/*": ["./node_modules/@angular/*"]
    }
  },
  // ...
}
```

In my library config, I removed the `enableIvy: false` key so I built my library using Angular 11 with Ivy.

**Comment by domiSchenk** [comment]
Just got the same error with Angular 11 and Ivy.

Did anyone find a solution?

**Comment by hoermillerj** [comment]
I ran into the same issue yesterday, but managed to fix it. I started by placing my stencil components project and the angular library into the same parent folder. And instead of adding a path entry to the project that consumes the Stencil Angular library I added one to the Angular Stencil Library. I added 

`"paths": {
      "stencil-library": ["../stencil-library/*"]
    }`
    
to the tsconfig.lib.json file. The entry is a relative path to my stencil components project. 
Then I created a module in my Stencil Angular Project which is exported in the public-api.ts file. This module declares and exports the stencil components from the proxies.ts file. And then (and I think this is the most important part) I imported and executed the defineCustomElements function from the stencil loader inside this module. This is what it looks like:

```
import { CommonModule } from '@angular/common';
import { ModuleWithProviders, NgModule } from '@angular/core';

import { MyComponent } from './directives/proxies';

import { defineCustomElements } from 'stencil-library/loader'
defineCustomElements(window);

const DECLARATIONS = [
  // proxies
  MyComponent
];

@NgModule({
  declarations: DECLARATIONS,
  exports: DECLARATIONS,
  providers: [],
  imports: [CommonModule],
})
export class ComponentLibraryModule {
  static forRoot(): ModuleWithProviders<ComponentLibraryModule> {
    return {
      ngModule: ComponentLibraryModule,
      providers: []
    }
  }
}
```
