### ISSUE TITLE
feat(angular): omit output related imports for components with no event #330

### ISSUE THREAD

**Issue by KariiO** [ionic-team/stencil-ds-output-targets#331]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

This is valid only for the `angular-output-target` package.

Don't provide import entries that are not required for components to work.
Components that do not have any events does not require to import these 2 entries that currently are always delivered:
`import { EventEmitter } from '@angular/core';`
`import { proxyOutputs } from './angular-component-lib/utils';`

### Describe the Use Case

This feature will solve problem where TypeScript compiler complains about unused locals (`"noUnusedLocals": true`) and any other static code analyze tool that has ability to find unused imports (eg. eslint `unused-imports/no-unused-imports`).

### Related Code

https://github.com/ionic-team/stencil-ds-output-targets/pull/330

**Comment by sean-perkins** [comment]
Hello @KariiO thanks for this request!

While we will track it as a feature (new improvement), I think we can likely target this as a patch fix. 

I appreciate you opening a PR to improve this and will take at that shortly!
