### ISSUE TITLE
bug: control entire conponent render by props

### ISSUE THREAD

**Issue by mehrabix** [ionic-team/stencil-ds-output-targets#353]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

3.2.1

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.7.0

### Current Behavior

I want to render entire component by setting a props but it does not work and in first render page it renders also my component js.
here is my stenciljs component file : 
https://github.com/prismaui/prismaui/blob/master/packages/core/src/components/toast/toast.tsx
i add such a condition for rendering base on props change on render method: 
    // if (!this.show) {
    //   return null
    // }

### Expected Behavior

shoud not render anything if nothing is on render method

### Steps to Reproduce

i create a toast component for example i add a condition on render method and add a watcher on props @Watch('show'). i expect when i change props from outside component shoud load but it renders without setting show props to true. i can render conditionally in angular with ngIf and it works fine but i want it to control by a props. is that posible?

### Code Reproduction URL

https://github.com/prismaui/prismaui

**Comment by sean-perkins** [comment]
Hello @mehrabix,

The default wrappers that are generated will not handle this behavior currently. In similar scenarios in Ionic Framework, we manually create the wrapper: https://github.com/ionic-team/ionic-framework/blob/main/packages/angular/src/directives/overlays/modal.ts#L83

You can then use your property to conditionally mount the template (the web component).

```ts
@Component({
  selector: 'prm-toast',
  template: `<ng-container *ngIf="show">
    <ng-container [ngTemplateOutlet]="template"></ng-container>
  </ng-container>
  `
})
class ToastComponent {

  @ContentChild(TemplateRef, { static: false }) template: TemplateRef<any>;

  @Input() show: boolean;

  constructor() {
    // proxyOutputs
  }

}
```

This code is a simplified version to demonstrate the `ng-container`/`ng-template` usage.

**Comment by christian-bromann** [comment]
@mehrabix let me know if you have further questions on this topic or a concrete proposal on how to improve the current experience. I will go ahead and close the issue but happy to re-open.
