### ISSUE TITLE
feat: Support for tsconfig Compiler Options "noUncheckedIndexedAccess"

### ISSUE THREAD

**Issue by tfrijsewijk** [ionic-team/stencil-ds-output-targets#355]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

I would like to enforce `"noUncheckedIndexedAccess": true` in my React library.

The following Stencil code then fails:

* https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/react-component-lib/createComponent.tsx#LL58C55-L58C55
* https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/react-component-lib/utils/attachProps.ts#L23
* https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/react-component-lib/utils/attachProps.ts#L25
* https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/react-component-lib/utils/case.ts#L7

### Describe the Use Case

Stricter code for React wrapper libraries. No more accidental "Object is possibly 'undefined'.".

### Additional Information

I can create a PR.

**Comment by sean-perkins** [comment]
Hello @tfrijsewijk thanks for opening this issue.

If you would like to submit a PR for these changes, I would be happy to review it.

**Comment by tfrijsewijk** [comment]
OK! Please allow me to find some time to resolve this issue.

**Comment by christian-bromann** [comment]
As we have moved to `@lit/react` we got rid of these files. So I will go ahead and close this issue. Thanks for reporting.
