### ISSUE TITLE
bug: ClassName not transformed and appplied when using Serverside Rendering

### ISSUE THREAD

**Issue by mayerraphael** [ionic-team/stencil-ds-output-targets#360]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.23

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.5.3

### Current Behavior

When using className property on a Stencil component wrapper, the className is only applied on hydration. The className property is not applied when using NextJS serverside rendering.

The problems seems to be that className is only transformed on `componentDidMount`, which does not trigger using serverside rendering (the Stencil hydrate package).

See: https://github.com/ionic-team/stencil-ds-output-targets/blob/3e1aaf6444016046cd9d8c7e6656e0693a74a5e1/packages/react-output-target/react-component-lib/createComponent.tsx#L53

You deconstruct props and assign className to a variable, but it is never used.

This bug can cause layout shifts because classNames are only applied once the component is hydrated.

### Expected Behavior

ClassNames should be transformed to a class attribute on first run, not after componentDidMount.

### Steps to Reproduce

```tsx
<my-component className="123" />
```

### Code Reproduction URL

donothave.com

**Comment by sean-perkins** [comment]
@mayerraphael a simple reproduction of a NextJS app with this problem would help us with verifying the issue against a proposed fix. 

I'm not entirely sure why `className` is not passed into the `newProps` when constructing the element wrapper, but that would be where I would likely start to see if assigning it directly on the element resolves the issue in your environment. 

Is this an issue you would be open to contributing towards?
