### ISSUE TITLE
ts error when adding style and class to a component directly in vue

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil-ds-output-targets#363]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

When adding `style` and `class` directly to a component in `vue` `ts` reports an error, but this is something that `vue` components should normally accept, I don't think it's necessary to add a `prop` of `style` and `class` for every component, can't this problem be solved from the time of building the `vue library`? It's in effect, but the `ts` error reporting is really hard to swallow! Since `react library` doesn't report this error when used normally, I wonder if this could be standardized? So that `vue library` can also be passed normally.

### Describe the Use Case

When adding `style` and `class` directly to a component in `vue` `ts` reports an error, but this is something that `vue` components should normally accept, I don't think it's necessary to add a `prop` of `style` and `class` for every component, can't this problem be solved from the time of building the `vue library`? It's in effect, but the `ts` error reporting is really hard to swallow! Since `react library` doesn't report this error when used normally, I wonder if this could be standardized? So that `vue library` can also be passed normally.

**Comment by wabi-habi** [comment]
> Hey @wabi-habi 👋
> 
> I'm going to move this issue to the github.com/ionic-team/stencil-ds-output-targets repo, which is where our Vue + React output target code lives. Can you please build a minimal reproduction case for the team to take a look at? It greatly helps expedite looking into issues that are reported. Thanks!

Okay, thank you very much.

**Comment by wabi-habi** [comment]
I've tested it, and as long as you give `style` and `class` types to each component when packaging, ts doesn't report errors!

**Comment by wabi-habi** [comment]
@rwaskiewicz Hi 👋, any progress on this issue?

**Comment by rwaskiewicz** [comment]
@wabi-habi can you please create a reproduction case for the team to look at? We are currently unable to move further without one. Please see this [note from ionitron-bot a few weeks back](https://github.com/ionic-team/stencil-ds-output-targets/issues/363#issuecomment-1640152315):

> Thanks for the issue! This issue has been labeled as needs reproduction. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in a Stencil project and provide a way for us to access it (GitHub repo, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.

**Comment by wabi-habi** [comment]
> @wabi-habi can you please create a reproduction case for the team to look at? We are currently unable to move further without one. Please see this [note from ionitron-bot a few weeks back](https://github.com/ionic-team/stencil-ds-output-targets/issues/363#issuecomment-1640152315):
> 
> > Thanks for the issue! This issue has been labeled as needs reproduction. This label is added to issues that need a code reproduction.
> > Please reproduce this issue in a Stencil project and provide a way for us to access it (GitHub repo, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> > If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.

OK, take a look at the program: [https://github.com/ayangweb/stencil-test.git](https://github.com/ayangweb/stencil-test.git)

<img width="614" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/99811051/abc669e4-c123-4436-90b8-29a9a1652ae4">

<img width="564" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/99811051/46c91fe1-2230-429e-a18d-b01e03222735">

**Comment by wabi-habi** [comment]
@rwaskiewicz Hey👋, any progress on this issue?

**Comment by ayangweb** [comment]
Hey @rwaskiewicz 👋, I've submitted a [pr](https://github.com/ionic-team/stencil-ds-output-targets/pull/379) on this issue, check it out sometime!

**Comment by ayangweb** [comment]
Hey @sean-perkins 👋 The choice to introduce components in order to have better ts type hints also resulted in `style`, `class`, and `slot` not having a type and reporting an error!

<img width="913" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/75017711/6c0c4c30-7d08-4a7d-8600-fc58fa8891b9">

<img width="795" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/75017711/e8c796be-d867-4226-bcc6-8ea611fd92cd">

It even reports errors when using native events as well!

<img width="1029" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/75017711/b8b7f3d0-df9a-4801-8ced-812e37f89847">
