### ISSUE TITLE
At directivesProxyFile the @Component decorator is missing the output event array

### ISSUE THREAD

**Issue by adoumas** [ionic-team/stencil-ds-output-targets#389]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

3.4.1

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.8.2

### Current Behavior

At "generate-angular-component.ts" file line 47

`
@Component({

  selector: '${tagName}',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  // eslint-disable-next-line @angular-eslint/no-inputs-metadata-property
  inputs: [${formattedInputs}], ${standaloneOption}

})
`

and on line 29

`

    if (hasInputs) {
        proxyCmpOptions.push(`\n  inputs: [${formattedInputs}]`);
    }

    if (hasMethods) {
        proxyCmpOptions.push(`\n  methods: [${formattedMethods}]`);
    }
`

### Expected Behavior

Should be like this so we can use it on angular as event (myCustomEvent)="handleCustomEvent($event)"

`
@Component({

  selector: '${tagName}',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  // eslint-disable-next-line @angular-eslint/no-inputs-metadata-property
  inputs: [${formattedInputs}],
  outputs: [${formattedOutputs}],
  ${standaloneOption},

})
`

`

    if (hasInputs) {
        proxyCmpOptions.push(`\n  inputs: [${formattedInputs}]`);
    }

    if (hasOutputs) {
        proxyCmpOptions.push(`\n  outputs: [${formattedOutputs}]`);
    }

    if (hasMethods) {
        proxyCmpOptions.push(`\n  methods: [${formattedMethods}]`);
    }
`

### Steps to Reproduce

Just try to build angularOutputTarget

### Code Reproduction URL

https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/angular-output-target/src/generate-angular-component.ts

### Additional Information

I hope not to miss something and i can't use the output decorator

`
<my-custom-element (myCustomEvent)=""></my-custom-element>
`

**Comment by sean-perkins** [comment]
👋 can you provide a reproduction app/stencil project that experiences this problem?

We use the output target with Ionic Framework and the events are bound correctly. The `outputs` array will not be written if the component does not have any decorated `@Event()` properties.

**Comment by m-thompson-code** [comment]
A workaround to this issue that I've used is to define a `HTMLElementTagNameMap` where I define event listeners for each Event:

```ts
/** src/my-types.d.ts */
declare global {
  type EventName = "my-event";
  interface HTMLMyComponentElement {
      addEventListener<EventName>(type: EventName, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<boolean>) => any, options?: boolean | AddEventListenerOptions): void;
      addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
      removeEventListener<EventName>(type: EventName, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<boolean>) => any, options?: boolean | EventListenerOptions): void;
      removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }

  interface HTMLElementTagNameMap {
      "my-component": HTMLMyComponentElement;
  }
}
```

I've created a PR to make this part of Stencil's compiler: https://github.com/ionic-team/stencil/pull/4909
And if you can use this output target to generate these event listener types for your project: https://github.com/m-thompson-code/event-listener-types-output-target#event-listener-types-output-target
