### ISSUE TITLE
bug: [React] when updating the slot content the component looses it's style

### ISSUE THREAD

**Issue by pedroresende** [ionic-team/stencil-ds-output-targets#393]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.3.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.5.3

### Current Behavior

If the content of the slot is replaced after the element is created the element looses it's style

https://github.com/ionic-team/stencil-ds-output-targets/assets/951377/2a85f607-9b3b-4e37-bfd5-fd06ba47a305

### Expected Behavior

To update the slot content and the wrapper to continue to work as expected

### Steps to Reproduce

1. Add a stencil webcomponent with a slot with provided content
2. Replaced the  content of the slot

```tsx
import Head from "next/head";
import { MyButton } from "@pedroresende/css-error";
import { useState, useEffect } from "react";

export default function Home() {
  const [hasLoaded, setLoaded] = useState(false);
  const [buttonText, setButtonText] = useState("hi");

  useEffect(() => {
    if (!hasLoaded && typeof window !== undefined) {
      setLoaded(true);
    }
  }, [hasLoaded]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p style={{ margin: "10px" }}>
          <input
            onChange={(e) => {
              setButtonText(e.target.value);
            }}
            defaultValue={buttonText}
          />
        </p>
        {hasLoaded && <MyButton>{buttonText}</MyButton>}
      </main>
    </>
  );
}
```

### Code Reproduction URL

https://github.com/pedroresende/css-removal-bug

**Comment by pedroresende** [comment]
Just found an workaround, if you add a React Fragment `<></>` around the slot it won't loose it's style and syntax

**Comment by christian-bromann** [comment]
This should be resolved with the latest version of `@stencil/react-output-target`. Let me know if it still poses an issue and I am happy to re-open.

**Comment by jeffplloyd** [comment]
@christian-bromann just tested this with 0.7.1 and the issue still remains when dynamically changing the text. Note the component I'm seeing this issue with is **not** shadow enabled.
