### ISSUE TITLE
[React] TypeError: head.querySelector is not a function

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil-ds-output-targets#42]
When using componentes generated with this plugin in Next.js, server page load throw a TypeError: head.querySelector is not a function because this plugin auto initialize CustomElement even if there is no document or window element.

Related to https://github.com/ionic-team/stencil/issues/2374

**Comment by jthoms1** [comment]
Closing this because it is a duplicate of #56. Thanks!
