### ISSUE TITLE
react-output-target SSR not passing props

### ISSUE THREAD

**Issue by nowseemee** [ionic-team/stencil-ds-output-targets#43]
Hi!

When I use react-output-target@0.0.6, the props are being removed from the initial render which causes missing data when doing SSR.

Here is how to reproduce:
https://github.com/nowseemee/react-proxy-bug-repro

Here is what I think the fix is:
https://github.com/ionic-team/stencil-ds-plugins/commit/49a0219e73f1d416ddfa653b812d7ce7b8e20c5e

Any reason for manipulating props in the render method? I think all manipulation  should takes place in [componentDidUpdate](https://github.com/ionic-team/stencil-ds-plugins/blob/master/packages/react-output-target/react-component-lib/createComponent.tsx#L30).

Let me know, thanks!

**Comment by patrickhaug** [comment]
Yes, I made a similar fix in one of my projects .. Is there reason why they are not passed? I don't know yet .. with this fix there is the normal react props missmatch warning, right?

**Comment by nowseemee** [comment]
This issue was fixed by https://github.com/ionic-team/stencil-ds-output-targets/commit/5dad557b1382ef0e41bb640b584ed004fe47ce41 - Many thanks!
