### ISSUE TITLE
bug(react): empty className not applied (includeImportCustomElements: true)

### ISSUE THREAD

**Issue by danielleroux** [ionic-team/stencil-ds-output-targets#440]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.18.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.5.3

### Current Behavior

`includeImportCustomElements: true` removes the hydration class from the web component. This cause an issue regarding applying and removing classes from elements.

Demo:
```tsx
function App() {
  const [value, setValue] = React.useState(false);

  return (
    <div>
      <MyComponent className={value ? 'is-red' : ''}>
        Should apply 'is-red' = {value ? 'true' : 'false'}
      </MyComponent>

      <OtherMyComponent className={value ? 'is-red' : ''}>
        Should apply 'is-red' = {value ? 'true' : 'false'}
      </OtherMyComponent>

      <button onClick={() => setValue(!value)}>Test 123</button>
    </div>
  );
}
```

If you start toggle the value state you will see that after a cycle the `is-red` class should be removed again from the element but this does not happen due this check:

https://github.com/ionic-team/stencil-ds-output-targets/blob/0eb22ba25fa808a4c71f25001e2640ac7a941405/packages/react-output-target/react-component-lib/utils/attachProps.ts#L8-L10

This issue is only happing with the following stencil.config:
```
    reactOutputTarget({
      componentCorePackage: 'other-lib-code',
      proxiesFile: '../other-lib-code-react/lib/components/stencil-generated/index.ts',
      includeImportCustomElements: true,
      includePolyfills: false,
      includeDefineCustomElements: false,
    }),
    {
      type: 'dist-custom-elements',
      dir: 'components',
      copy: [
        {
          src: '../scripts/custom-elements',
          dest: 'components',
          warn: true,
        },
      ],
      includeGlobalScripts: false,
    },
```
(used in ionic)

### Expected Behavior

ClassName check should not ignore a new empty className

### Steps to Reproduce

1. Checkout https://github.com/danielleroux/className-Issue
2. pnpm install
3. pnpm dev --filter my-app
4. Toggle Button some times

### Code Reproduction URL

https://github.com/danielleroux/className-Issue

**Comment by christian-bromann** [comment]
@danielleroux this bug should be fixed with the latest version of `@stencil/react-output-target`. Let me know if not and I am happy to re-open this.
