### ISSUE TITLE
bug: build sometimes does not generates react output

### ISSUE THREAD

**Issue by shivajivarma** [ionic-team/stencil-ds-output-targets#444]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.11.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.5.3

### Current Behavior

Sometimes react output is not present after build. `dist/generated/goatui-react/`.

It is strange every alternative build generates the react output.

### Expected Behavior

Every time react output should be generated.

### Steps to Reproduce

   ```js
reactOutputTarget({
      componentCorePackage: '@goatui/components',
      proxiesFile: 'dist/generated/goatui-react/index.ts',
    }),
```

### Code Reproduction URL

https://github.com/goatui/components

**Comment by christian-bromann** [comment]
Hey @shivajivarma 👋  thanks for raising the issue. I believe this should be resolved with the latest version of `@stencil/react-output-target`. If you still encounter this problem, please let me know and I am happy to re-open the issue.
