### ISSUE TITLE
[react-output-target] bug: generated components.ts using absolute paths in an Nx monorepo

### ISSUE THREAD

**Issue by dgonzalezr** [ionic-team/stencil-ds-output-targets#457]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.20.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.6.0

### Current Behavior

After the latest changes on [this PR](https://github.com/ionic-team/stencil-ds-output-targets/pull/452), it seems that the `@stencil/react-output-target` package generates the `components.ts` file using absolute paths when the project structure is a monorepo environment with NX.

![image](https://github.com/user-attachments/assets/18987675-22a6-423b-879b-4a3860754338)

> [!IMPORTANT]
> **Please, note that this issue does not occur with the previous version** of `@stencil/react-output-target` v0.5.3.

### Expected Behavior

The `@stencil/react-output-target` package is designed to generate the `components.ts` file with the correct paths.

### Steps to Reproduce

Follow the steps described in the **Issue 2** of the reproduction code below

### Code Reproduction URL

https://github.com/dgonzalezr/nx-stencil

**Comment by dgonzalezr** [comment]
Ok, this might be a false issue and mostly a misconfiguration. We used to resolve the path (because of some Windows issues in the past) but after removing that and using the relative path it seems to work as expected 🙂

![image](https://github.com/user-attachments/assets/ebbb7436-6a45-41f8-9805-ebaa509defdc)

![image](https://github.com/user-attachments/assets/99cd8e80-fd96-4552-aac9-d7fa6dcd37c1)

I will continue with some more testing and update or close this issue as needed.

**Comment by dgonzalezr** [comment]
After another round of tests, it has become apparent that a `customElementsDir` is likely needed. Our project setup uses certain plugins that require resolving absolute paths; not resolving these paths results in a compilation error. I believe this issue was also present before v0.6.0, but there we had the option to set the `customElementsDir`, even if it's equal to its default value.

Is it possible to consider adding `customElementsDir` as an option in the target setup?

**Comment by christian-bromann** [comment]
Hey @dgonzalezr 👋  what is the `customElementsDir` suppose to allow users to change?

**Comment by dgonzalezr** [comment]
@christian-bromann the same as it does with v0.5.3: https://stenciljs.com/docs/react#customelementsdir

In v0.6.0 [import declarations are built](https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/src/react-output-target/create-stencil-react-components.ts#L51) using:
* stencilPackageName
* customElementsDir
* tagName

In my case, because of [my setup shown here](https://github.com/Endava/BEEQ/blob/main/packages/beeq/stencil.config.ts#L86), when resolving the path where to generate the components.ts from `stencil.config.ts` I need to resolve the path for generating components.ts using node resolve with __dirname. In v0.6.0, it would look like this:

```ts
  react({
    outDir: resolve(__dirname, '../beeq-react/src/').replace(/\\/g, '/'),
  }),
```

The issue is that the resolved path, which is absolute, also gets added to the customElementsDir (refer to the screenshot previously mentioned). If I could set a fixed value for customElementsDir, it might help resolve my issue.

```ts
  react({
    outDir: resolve(__dirname, '../beeq-react/src/').replace(/\\/g, '/'),
    customElementsDir: 'whatever'
  }),
```

This way, the import statement would adhere to that specified value and generate:

```js
import { ... } from '<stencilPackageName>/whatever/<tagName>';
```

I hope this makes sense. If not, feel free to ask for more details.

**Comment by christian-bromann** [comment]
It seems like this is being tackled in #461
