### ISSUE TITLE
bug: 9.0 Using valueAccessorConfigs does not add the base value-accessor file to the generated outputs

### ISSUE THREAD

**Issue by istvanherbak** [ionic-team/stencil-ds-output-targets#469]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.21.0

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

9.0

### Current Behavior

All my custom value-accessors are generated for the selectors, however the referenced base vale-accessor directive file is not added to the output folder.

### Expected Behavior

The previously added base value-accessor.ts file is also present in the output folder.

### Steps to Reproduce

Create a valueaccessor that is targeting 'value'.
Build the stencil project and find that the generated file is trying to import ./value-accessor.ts which is missing.

### Code Reproduction URL

https://github.com/istvanherbak/stencil

**Comment by Loic57** [comment]
I have the same issue

**Comment by dgonzalezr** [comment]
> I have the same issue but it depends, sometimes I have a folder named "value-accessor.ts" with a file inside named "value-accessor.ts"
> 
> Sometimes nothing is created.
> 
> But I never have the classic value-accessor.ts file created so I created manually a script to detect if the value-accessor.ts foler exists and if yes, I move the file outside the folder.

Yes, I've been facing this issue for quite some time and also used the same workaround, a script that will move the `value-accessor.ts` file to the right path. [You can see it 👉🏼  here](https://github.com/Endava/BEEQ/blob/main/packages/beeq-angular/scripts/fix-value-accessor-path.ts).

**Comment by christian-bromann** [comment]
Hey folks 👋 thanks for raising the issue. I've identified the bug and working on a fix.
