### ISSUE TITLE
bug: All stencil components are imported in Angular even if only one is called

### ISSUE THREAD

**Issue by Loic57** [ionic-team/stencil-ds-output-targets#478]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.2

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.9.0

### Current Behavior

I don't know if this "bug" is related to stencil or output-target (for me it's a mix of both) so I'm trying to get help here. Sorry if I'm not in the good place.

I followed this documentationt to build a monorepo with stencil and angular : https://stenciljs.com/docs/angular
Nothing less, nothing more.

When running my angular app I can see in the network tab in my console that my two stencil components are loaded whereas I only need one.

![image](https://github.com/user-attachments/assets/36b37d33-42c3-42cc-a7f1-88cf506aa296)

In my app.component.ts (angular 18.2 in standalone mode) I call only "my-component" but my two components are called in the console.

```
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { MyComponent } from 'component-library';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MyComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'my-app';
}
```

### Expected Behavior

I would like to load only the right component, not everything at once.

### Steps to Reproduce

git clone https://github.com/Loic57/stencil-angular-18
npm i (be sure to have lerna installed)
go to packages/stencil-library and run : npm run build
go to packages/angular-workspace and run : npx -p @angular/cli ng build component-library
go to packages/angular-workspace/projects/my-app and run : npm run start

The browser should open on localhost:4200 and you should see "Hell, i'm a test" which is shipped by default with stencil.

But if you inspect the network tab in the console you should see another component name created by myself but which is not called in app.component.ts

### Code Reproduction URL

https://github.com/Loic57/stencil-angular-18

### Additional Information

There is something which disturb me a lot.
In the documentation it says :
By default, the dist-custom-elements output target generates a single file per component, and exports each of those files individually.

But, in the angular documentation it says :
The configuration for the [Custom Elements](https://stenciljs.com/docs/custom-elements) output target must set the [export behavior](https://stenciljs.com/docs/custom-elements#customelementsexportbehavior) to single-export-module for the wrappers to generate correctly if using the scam or standalone output type.

So, in one side it says, "keep customElementsExportBehavior on default to have one component per file" and on the other side it says "change customElementsExportBehavior to 'single-export-module' if you need standalone components"

But single-export-module' regroups all the components into one index.js file.

I'm lost

**Comment by djount** [comment]
Hi !
Same issue here, at the beginning we thought it was an issue with Angular 18 but we did some tests on Angular 17 and 16.2 and this is the same.
All components are loaded at the same time. We have around 30 components built with stencil and the page is quite heavy.

Are there any solutions ?

**Comment by BertVdBrande** [comment]
I noticed the same thing.

I had a look inside the Angular output generator , unless I'm mistaken the 'generateProxies' will always write all Angular components to 1 single file.

https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/angular-output-target/src/output-angular.ts

``` 
const finalText = generateProxies(filteredComponents, pkgData, outputTarget, config.rootDir as string);

  await Promise.all([
    compilerCtx.fs.writeFile(outputTarget.directivesProxyFile, finalText),
    ...
```

While typing this I just realised something :
The `dist-custom-elements` documentation probably refers to the web component generation only => these files are indeed generated individually.

The Angular 'web component wrapper' generation is done via the 'angularOutputTarget' and while there is support to generate standalone components, there appears to be no support to generate the components in individual files.

**Comment by christian-bromann** [comment]
@Loic57 sorry for the late response. Our team is currently battling a lot of competing priorities and currently does not have the capacity to look into individual issues like these. We would appreciate any contributions to the project and happy to guide on technical questions. Thank you!

**Comment by BertVdBrande** [comment]
@Loic57 Not sure if this will fix your issue completely, however it's worth to note that Angular will not apply tree-shaking when running `ng serve` (called when running `npm start`) .

If you start angular the following way (from dir packages/angular-workspace) :
```
ng build my-app -c production
npx http-serve ./dist/my-app/browser/
```
and then browse + inspect the bundle content you will not find `component-2` anymore in the bundles, because it has been tree-shaken during the build phase.

Hope this helps :)

**Comment by Loic57** [comment]
@BertVdBrande You're totally right!

I have tried by myself and indeed in build mode all the components JS files are merged into one minified JS file which contains only the components imported in the TS files.

So for me it answers my question, I close the ticket
