### ISSUE TITLE
feat: just follow the semantic release versioning

### ISSUE THREAD

**Issue by yigityuce** [ionic-team/stencil-ds-output-targets#492]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

please immediately get back to the industry standards as versioning by using semantic release versioning. you introduce breaking change and only the minor version is changed in the version tag???? this is ridiculous. 

We have installed the @stencil/react-output-target@0.5.3 with the configuration below in package.json file:

`@stencil/react-output-target": "^0.5.3"`

and as others, except this package maintainers, we assume that there won't be any breaking change in the package. But....

you introduced a BC with version 0.6.x and guess what happens

in our pipelines with fresh install, it downloads the `0.7.1` because it is defined and used everyone in the world as defined in [here](https://docs.npmjs.com/about-semantic-versioning )

please align your strategy with the semantic versioning ASAP

### Describe the Use Case

described above

**Comment by christian-bromann** [comment]
@yigityuce thanks for this feedback!

While in general there has been no statement from the Ionic team that we are using SemVer for versioning, hence there should be no expectation that we do, we take user feedback like this serious and will discuss our versioning strategy internally. We will keep you updated on the results of these internal discussions.

Thank you!
