### ISSUE TITLE
ref prop of React Components is not working

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/stencil-ds-output-targets#51]
Hello folks

I have this code from a React project:
```
<IonPhaser ref={(ref) => console.log(ref)} game={game} initialize={initialize} />
```
But the **console.log** never runs, therefore **useRef** of **React** is not working:
```
import React, { useRef } from 'react'

export default function App () {
  const gameRef = useRef<HTMLIonPhaserElement>(null)
  const debug = () => {
    console.log('Reference', gameRef.current) // Always is null
  }

  return (
    <>
      <IonPhaser ref={gameRef} game={game} initialize={initialize} />
      <button onClick={debug}>Debug</button>
    </>
  )
}
```

This is the project: https://github.com/proyecto26/ion-phaser

Thanks in advance!
Regards

**Comment by WickyNilliams** [comment]
Also just discovered this same issue.

I notice @jthoms1 has been doing some work on master around refs - are those commits related to this bug?

**Comment by jthoms1** [comment]
I believe that this fixes the issue you outlined. I have tests for this use case.
