### ISSUE TITLE
bug: Missing overrides in angular value accessors

### ISSUE THREAD

**Issue by CosmicEvil** [ionic-team/stencil-ds-output-targets#515]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

18.0.0

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.9.0

### Current Behavior

When adding the value accessors for boolean and number, we are getting errors about the overrides not being there.
This is due to the accessors having a function that overrides something in the parent accessor but is not noted as override.

### Expected Behavior

The build should succeed instead of giving issues.

### Steps to Reproduce

1) Add new value accessors for angular in the stencil config.
2) Specifically for the boolean and number
3) When building the angular stencil output it breaks

### Code Reproduction URL

https://github.com/CosmicEvil/stencil-ds-output-targets

**Comment by christian-bromann** [comment]
Closing as a patch for this has been merged to the project.
