### ISSUE TITLE
feat: start to use major for breaking changes

### ISSUE THREAD

**Issue by felipefialho** [ionic-team/stencil-ds-output-targets#553]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

Currently, `stencil-ds-output-targets` maintains in `minor` (major.minor.patch) versions even when there have been breaking changes, such as the recent modifications to the `react-output-target` which altered the export format of React components

To better align with semantic versioning (SemVer), we could consider transitioning to a major.minor.patch versioning scheme. This would allow us to:

Major: For breaking changes like those introduced in the recent react-output-target modifications.
Minor: For new features that maintain backward compatibility.
Patch: For bug fixes.

### Describe the Use Case

This change would make it easier for developers to understand the impact of updates to `stencil-ds-output-targets` and to manage their dependencies accordingly

**Comment by christian-bromann** [comment]
Thanks for the feedback. The reason we have released recent changes to the React output target not as a major release was that we haven't had a proper v1.0 release. We understand this causes confusion and we will consider be more deliberate moving on.
