### ISSUE TITLE
SSR warnings in NextJS

### ISSUE THREAD

**Issue by sslotsky** [ionic-team/stencil-ds-output-targets#56]
Carrying over from #37 

[The library that I published is here](https://www.npmjs.com/package/@manifoldco/manifold-init-react) and is being used as follows:

```ts
import { ManifoldInit } from "@manifoldco/manifold-init-react/dist/components";

const Home = () => (
  <div className="container">
    <ManifoldInit env="stage" clientId="my-client-id" />
```

The app renders the component correctly but I've seen some warnings in NextJS.

## SSR - Unhandled promise rejection

When I run my NextJS dev server, my terminal shows following error the first time I load the app:

```
(node:13529) UnhandledPromiseRejectionWarning: TypeError: head.querySelector is not a function
    at Object.bootstrapLazy (/home/sam/taco-cloud-react/node_modules/@manifoldco/manifold-init/dist/cjs/index-1ab6c73d.js:825:44)
    at /home/sam/taco-cloud-react/node_modules/@manifoldco/manifold-init/dist/cjs/loader.cjs.js:8:16
(node:13529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't know if that's because NextJS is SSR and there's some code that shouldn't be running on the server side, but I tried rendering the component only when `process.browser` is defined and the error didn't go away, so it's hard to tell.

Again, the component renders fine on the page, but perhaps there are some places where SSR should be taken into account.

**Comment by christian-bromann** [comment]
With the latest version of `@stencil/react-output-target` we now provide a much better support for Stencil components in Next.js. If this still poses an issue for anyone using the latest version, please let me know and I can re-open the issue.
