### ISSUE TITLE
feat: add extend plugins option for react-output-targets

### ISSUE THREAD

**Issue by stout-ni** [ionic-team/stencil-ds-output-targets#576]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Describe the Feature Request

I would like to add a `plugins` option in the react-output-target options to perform some additional custom operations after the build is complete.

### Describe the Use Case

- For example, I are using SCSS in global-styles, but I want to generate a CSS file in the React package using `cachedGlobalStyle`.

### Describe Preferred Solution

```
// packages/react/src/react-output-target/react-output-target.ts
import type { Config, CompilerCtx, ComponentCompilerMeta } from '@stencil/core/internal';

export interface ReactOutputTargetOptions {
  /**
   * Plugins to extend the output target.
   */
  plugins?: Array<
    (config: Config, compilerCtx: CompilerCtx, components: ReadonlyArray<ComponentCompilerMeta>) => Promise<void>
  >;
}

async generator(_config, compilerCtx, buildCtx: BuildCtx) {
  await Promise.all(
    sourceFiles.map((sourceFile) => compilerCtx.fs.writeFile(sourceFile.getFilePath(), sourceFile.getFullText()))
  );

  await Promise.all((plugins || []).map((plugin) => plugin(_config, compilerCtx, buildCtx.components)));
}
```

### Additional Information

If this feature request is feasible, I would be happy to submit a pull request to contribute this feature. :)

**Comment by christian-bromann** [comment]
@stout-ni thanks for the suggestion. I think some more access to the build process would be very helpful. I just wonder if it makes more sense to extend the Stencil core plugins to achieve what you are looking for. Have you ever taken a look on https://stenciljs.com/docs/plugins and can you explain why additional plugins for the output target would be helpful?

**Comment by stout-ni** [comment]
> @stout-ni thanks for the suggestion. I think some more access to the build process would be very helpful. I just wonder if it makes more sense to extend the Stencil core plugins to achieve what you are looking for. Have you ever taken a look on https://stenciljs.com/docs/plugins and can you explain why additional plugins for the output target would be helpful?

@christian-bromann Thank you for your reply! Like the example I provided above, actually I just wanted quick access to cachedGlobalStyle to reduce the need for me to compile Sass into CSS 😂

But I've thought about it, I think you are right, and there are indeed very few scenarios where designing such a feature here would be beneficial. I will use the current plugins to write it, so this issue can be closed.
