### ISSUE TITLE
[Publish] New @react-output-target version in NPM with important updates.

### ISSUE THREAD

**Issue by victormath12** [ionic-team/stencil-ds-output-targets#58]
I'm having a problem with `@react-output-target  - version 0.0.6 (latest)`, when I'm trying to build the package the `tcs` I receive this throble:

```js
src/react-component-lib/createOverlayComponent.tsx(15,17): error TS2742: 
The inferred type of 'createOverlayComponent' 
cannot be named without a reference to 'react-dom/node_modules/@types/react'. 
This is likely not portable. A type annotation is necessary.
```

I saw that the commit [9d385ee](https://github.com/ionic-team/stencil-ds-output-targets/commit/9d385eeef3667d0b6dd17c28f50275ec5129d424) fixed this problem and it was merged with the master branch, but it is not available in version 0.0.6 in NPM.

so, when will you guys publish a new version with these important updates?

**Comment by jthoms1** [comment]
I am working on the release. I hope to have it out next week.

**Comment by victormath12** [comment]
Thanks @jthoms1 👍
