### ISSUE TITLE
react-component-lib folder requires @stencil/core?

### ISSUE THREAD

**Issue by edolix** [ionic-team/stencil-ds-output-targets#68]
Hello,

i've been using `react-output-target` following [this setup](https://github.com/ionic-team/stencil-ds-output-targets#stencil-config-setup-1) and upgrading to latest version i've got this issue.

`react-component-lib/interfaces.ts` has this import so, does it mean the React component lib requires @stencil/core as a devDependency now?

https://github.com/ionic-team/stencil-ds-output-targets/blob/ef562fdf84a817c87f1f588feadcd143b4ebece7/packages/react-output-target/react-component-lib/interfaces.ts#L1

Thanks!

**Comment by jthoms1** [comment]
hmm, That was missed.  It should not be needed. That is a pretty simple type so I will probably copy/paste it in.

**Comment by edolix** [comment]
Thanks @jthoms1 💯
