### ISSUE TITLE
@typescript-eslint/no-useless-constructor warning

### ISSUE THREAD

**Issue by sentience** [ionic-team/stencil-ds-output-targets#89]
createComponent.txt's `ReactComponent` class includes a constructor that does nothing:

https://github.com/ionic-team/stencil-ds-output-targets/blob/ca8e7078ca3d80bb8233bc2f7f4c3f5a2d61f9cc/packages/react-output-target/react-component-lib/createComponent.tsx#L39-L41

In a create-react-app project, ESLint complains about this:

>Compiled with warnings.
>
>./src/react-component-lib/createComponent.tsx
>  Line 39:5:  Useless constructor  @typescript-eslint/no-useless-constructor

**Comment by christian-bromann** [comment]
Closing as we have moved to `@lit/react` which made this code disappear.
