### ISSUE TITLE
Angular 10: Class is using Angular features but is not decorated

### ISSUE THREAD

**Issue by reda-alaoui** [ionic-team/stencil-ds-output-targets#90]
I am trying to use this library with Angular 10.
I get the following error when I try to build the Angular project:

```
src/directives/generated/value-accessor.ts:4:14 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.

4 export class ValueAccessor implements ControlValueAccessor {
```

This new behaviour seems to have been introduced by https://github.com/angular/angular/pull/36921.

Manually appending `@Directive()` to `ValueAccessor` fixes the issue:
```typescript
import {Directive, ElementRef, HostListener} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';

@Directive()
export class ValueAccessor implements ControlValueAccessor {
// ...
```

I wanted to create a pull request for that, but `@Directive` changed between Angular 9 and Angular 10.
In Angular 9, `@Directive()` requires a selector attribute, while in Angular 10, you can pass it without any option.

So maybe Stencil needs to be aware of the Angular version effectively used?

**Comment by mbulfair** [comment]
I ran into this error, I am using 0.0.2 of the output, but my output project has been upgraded to use 10.x of angular..

**Comment by Hamcker** [comment]
For me it occurs on an abstract class.

**Comment by Lampent** [comment]
> For me it occurs on an abstract class.

Same here.

**Comment by avchugaev** [comment]
Angular team, please let us write normal abstract/base classes. This limitation looks ridiculous. It forces me to decorate my abstract class just because it implements `OnDestroy` interface.

```ts
@Injectable() // 👈 I have to add this for no real reason to satisfy the compiler. why?!
export abstract class LocalStore<TState> extends StoreBase<TState> implements OnDestroy {
  ngOnDestroy(): void {
    this.complete();
  }
}
```

**Comment by reda-alaoui** [comment]
After upgrading from:
```json
{
  "@stencil/angular-output-target": "0.0.2",
  "@stencil/core": "1.15.0",
  "@stencil/sass": "1.3.2"
}
```
to
```json
{
    "@stencil/angular-output-target": "0.0.6",
    "@stencil/core": "2.6.0",
    "@stencil/sass": "1.4.1"
}
```

It just works without any workaround :tada:

**Comment by GLoganDR** [comment]
> After upgrading from:
> 
> ```json
> {
>   "@stencil/angular-output-target": "0.0.2",
>   "@stencil/core": "1.15.0",
>   "@stencil/sass": "1.3.2"
> }
> ```
> 
> to
> 
> ```json
> {
>     "@stencil/angular-output-target": "0.0.6",
>     "@stencil/core": "2.6.0",
>     "@stencil/sass": "1.4.1"
> }
> ```
> 
> It just works without any workaround 🎉

I'm using @stencil/angular-output-target v0.2.0, and I am still getting this issue. I get a warning that value-accessor.ts has no selector and "Cannot determine the module for class ValueAccessor in ****! Add ValueAccessor to the NgModule to fix it." Again, this appears to still be an issue.

**Comment by GLoganDR** [comment]
I downgraded to 0.0.5, and it's working. I'm sure I must be missing something or doing something wrong, but I'll keep it like this for now until further updates occur.
