### ISSUE TITLE
React Output Target deletes output if it already exists

### ISSUE THREAD

**Issue by dave-slash-null** [ionic-team/stencil-ds-output-targets#92]
I have configured my react output target to live in ./dist/react as follows:

```js
reactOutputTarget({
  proxiesFile: './dist/react/index.ts',
}),
```

When I run `stencil build` once, the proxies file and react-component-lib dir get created in ./dist/react.  However, if I run `stencil build` again the ./dist/react dir is being removed entirely.

So in order to rebuild react components I need to run `stencil build` twice.  Desired behavior would be to have the output target created with latest changes every time I run `stencil build`

**Comment by aeciolevy** [comment]
Same issue here.

**Comment by PMudra** [comment]
I think I have a similar issue, too. On my machine everything is working as expected. The files (in my case `components.ts` and `react-component-lib/`) are generated on every build. However, in the CI environment those files were just deleted and not all files would be generated again.

Error message:

```
src/components.ts(4,38): error TS2307: Cannot find module './react-component-lib' or its corresponding type declarations.
```

So, `components.ts` exists but the directory `react-component-lib/` does not.

My current workaround is to git ignore those generated files completely. That way they are generated on every build which is not bad IMO.

@dave-slash-null or @aeciolevy have you found the reason for this behavior or any solution?

**Comment by christian-bromann** [comment]
This issue should be not relevant anymore using the latest `@stencil/react-output-target`. Let me know if this still poses an issue for anyone and I am happy to re-open.
