### ISSUE TITLE
React output target / document is not defined in isCoveredByReact()

### ISSUE THREAD

**Issue by mhaegeleMHP** [ionic-team/stencil-ds-output-targets#98]
- @stencil/react-output-target": "^0.0.7"
- @stencil/core": "~1.14.0"

When using react output generated components do not work in SSR (like Next.js) because generated components try to use document without safety checking if document exists.

This was already fixed by https://github.com/ionic-team/stencil-ds-output-targets/pull/40/files but it got removed in v.0.0.7.

**Comment by viljamis** [comment]
We just ran into this as well today. Was working fine with previous release (0.0.6), but now the output target is a little broken for e.g. users of Next.js.
